org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Используем локальный aapt2 (Termux ARM64), Gradle сам скачивает x86-64.
android.aapt2FromMavenOverride=/data/data/com.termux/files/home/android-sdk/build-tools/35.0.0/aapt2
# Отключаем параллельные процессы для экономии памяти на устройстве.
org.gradle.parallel=false
org.gradle.caching=true
